numerical_columns:
 - writing_score
 - reading_score

categorical_columns:
    - gender
    - race_ethnicity
    - parental_level_of_education
    - lunch
    - test_preparation_course

target_column:
 - math_score
  

